### ISSUE TITLE
Missing mesh in the project

### ISSUE THREAD

**Issue by zurex** [Brackeys/RPG-Tutorial#2]
Does the project missing bridge and ground mesh?
When i import the project to unity(version 2017.1.1f1 for mac), i can not found the bridge in 
 the scene.And if i click the Bridge , it shows MeshFilter component is missing mesh.
I checked all the resource and still not found where it is.
So is there something wrong?

**Comment by shimmery1210** [comment]
You need to install Blender software to have the mesh imported properly.
Brackeys used Blender file instead of fbx file for the bridge and the
ground models, which can only be recognized in Unity when you have Blender
software installed on the computer. So go to download and install Blender
and then open the project, you will find the bridge and ground imported
properly.

Unity claimed that it can "recognize" many 3D applications scene file, such
as Maya/Blender/C4D/etc. However, you still need to have those 3d
applications installed as well. My suggestion is to use .fbx file for your
project if you wish to export your assets to other people to use.


2018-01-13 18:14 GMT+11:00 朱剑超 <notifications@github.com>:

**Comment by zurex** [comment]
@shimmery1210 Thanks for a lot, i fixed it now.
What's more, it will be better to add in README for a tutorial.
